"""
Financials table: retrieves the actual income statement, balance sheet,
and cash flow statement tables from a company filing (verbatim, not
LLM-summarized) and parses them into structured rows/columns for display.
"""

import re
from app.graph.pipeline import vector_store

STATEMENT_QUERIES = {
    "income_statement": "net sales cost of sales gross margin operating income net income per share",
    "balance_sheet": "total current assets total liabilities total shareholders equity cash and cash equivalents",
    "cash_flow": "cash generated by operating activities investing activities financing activities",
}

CANDIDATES_PER_STATEMENT = 8
MIN_NUMERIC_CELLS = 6

REQUIRED_KEYWORDS = {
    "income_statement": [["net sales", "total net sales", "revenue", "net revenue"], ["net income", "earnings per share", "diluted"]],
    "balance_sheet": [["total assets"], ["total liabilities"]],
    "cash_flow": [["operating activities"], ["cash and cash equivalents", "beginning of", "end of"]],
}

UNITS_PATTERN = re.compile(r"\(in (millions|thousands|billions)", re.IGNORECASE)


def _contains_any(text, options):
    return any(opt in text for opt in options)


def _clean_row(row):
    cleaned = []
    i = 0
    while i < len(row):
        cell = row[i].strip()
        if cell == "$" and i + 1 < len(row):
            next_cell = row[i + 1].strip()
            cleaned.append(f"${next_cell}" if next_cell else "")
            i += 2
        else:
            cleaned.append(cell)
            i += 1
    return cleaned


def _parse_markdown_table(markdown):
    lines = [line.strip() for line in markdown.strip().split("\n") if line.strip()]
    if len(lines) < 2:
        return None

    def parse_row(line):
        cells = line.strip().strip("|").split("|")
        return [c.strip() for c in cells]

    headers = _clean_row(parse_row(lines[0]))
    data_rows = [_clean_row(parse_row(line)) for line in lines[2:]]

    return {"headers": headers, "rows": data_rows}


def _looks_like_real_data_table(parsed):
    if not parsed:
        return False

    number_pattern = re.compile(r"\(?-?\$?\d[\d,]*\)?%?")
    numeric_cell_count = 0

    for row in parsed["rows"]:
        for cell in row:
            if number_pattern.fullmatch(cell.strip()):
                numeric_cell_count += 1

    return numeric_cell_count >= MIN_NUMERIC_CELLS


def _detect_units(company_name):
    docs = vector_store.similarity_search(
        "in millions except per share amounts consolidated financial statements",
        k=6,
        filter={"company": company_name},
    )
    for doc in docs:
        match = UNITS_PATTERN.search(doc.page_content)
        if match:
            return match.group(1).lower()
    return None


def get_financial_tables(company_name):
    result = {}

    for key, query in STATEMENT_QUERIES.items():
        docs = vector_store.similarity_search(
            query, k=CANDIDATES_PER_STATEMENT,
            filter={"$and": [{"company": company_name}, {"is_table": True}]},
        )

        chosen = None
        keyword_groups = REQUIRED_KEYWORDS[key]

        for doc in docs:
            parsed = _parse_markdown_table(doc.page_content)
            if not _looks_like_real_data_table(parsed):
                continue

            lowered_text = doc.page_content.lower()
            if all(_contains_any(lowered_text, group) for group in keyword_groups):
                chosen = parsed
                break

        result[key] = chosen

    result["units"] = _detect_units(company_name)

    return result
